on: [push, pull_request]
name: Test with Docker
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      
      - name: Test main package
        run: go test -v ./...

      - name: Test SQL
        working-directory: ./driver/sql
        run: go test -v ./...

      - name: Test drivers with databases
        working-directory: ./driver/tests
        run: go test -v ./...
